#!/bin/bash

gcc -g -Wall -o $2 ${2}.c 1> $1 2>> $1

success=`grep -L -e "warning" -e "error" $1`

if [ "$success" = "${1}" ]; then
    echo "Compilation succeeded"
    exit 0
else   
    echo "Compile failed"
    exit 1
fi 
