#!/bin/bash

#********************************************************************
# script name: testCompilation
# Descriptiuon: compiles app and reports errors
# Paramaters: $1 logfile, $2 fiel to compile
# Return Value: 0 success 1 fail
#********************************************************************

gcc -g -Wall -o $2 ${2}.c 1> $1 2>> $1

# search output for errors or warnings
success=`grep -L -e "warning" -e "error" $1`

if [ "$success" = "${1}" ]; then
    echo "Compile succeeded"
    exit 0
else   
    echo "Compile failed"
    exit 1
fi 
