#!/bin/bash

# input is logfile, program name, input file

valgrind --tool=memcheck --error-exitcode=1 ./$2 <$3 2>$1 >/dev/null

if [ "$?" = "1" ]; then 
    echo "Memory test failed"
    exit 1
else
    echo "Memory test passes"
fi


